---

- name: Configure APT
  ansible.builtin.include_tasks:
    file: tasks/apt.yml

- name: Configure web server
  ansible.builtin.include_tasks:
    file: tasks/webserver.yml

- name: Install MultiFlexi packages
  ansible.builtin.include_tasks:
    file: tasks/multiflexi.yml

- name: Configure database
  ansible.builtin.include_tasks:
    file: tasks/database.yml

- name: Configure PHP
  ansible.builtin.include_tasks:
    file: tasks/php.yml

- name: Configure MultiFlexi Zabbix integration
  ansible.builtin.include_tasks:
    file: tasks/zabbix.yml
  when: multiflexi_server_zabbix_host
