---
# - name: Install system TODO
#   ansible.builtin.apt:
#     name: ["abraflexi-webhook-acceptor-mysql", "multiflexi-mysql"]
#     state: present

- name: Install MultiFlexi multi package
  ansible.builtin.apt:
    name: "multiflexi-{{ multiflexi_server_database_type }}"
    state: present
  become: true
  tags: ['multiflexi']

- name: Install MultiFlexi Commandline interface
  ansible.builtin.apt:
    name: 'multiflexi-cli'
    state: present
  become: true
  tags: ['multiflexi', 'cli']

- name: Install MultiFlexi Web interface
  ansible.builtin.apt:
    name: 'multiflexi-web'
    state: present
  become: true
  when: multiflexi_web_interface | default(true) | bool
  tags: ['multiflexi', 'web']
